### ISSUE TITLE
Text-embeddings

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/SlideInsight#10]
In order to know which slides are related to each other and group slides by content, it might be useful to explore text-embeddings. To minimize costs, I propose to try [mxbai-embed-large](https://ollama.com/library/mxbai-embed-large) and [ollama-python](https://github.com/ollama/ollama-python). 

We could reuse infrastructure developed in #8 to turn PDFs into images, then images into text, and text into embeddings. The embedding could then be explored interactively using a notebook similar to [this one](https://github.com/haesleinhuepf/stackview/blob/main/docs/sliceplot.ipynb).

**Comment by lea-33** [comment]
Thanks! I am working on it. I just wanted to add that in the [example notebook](https://github.com/haesleinhuepf/stackview/blob/main/docs/sliceplot.ipynb) the code for the stackview.sliceplot is somehow not working correctly as you don't actually see the plot! But it worked after i tried it myself, so it should work actually.

**Comment by haesleinhuepf** [comment]
Don't worry about the interactive plot. This doesn't render on the github website :-)

**Comment by lea-33** [comment]
> Don't worry about the interactive plot. This doesn't render on the github website :-)

Alright! I also tried to do it in the Notebook I downloaded but still I can't really select the data points [like it is supposed to be](https://github.com/haesleinhuepf/stackview/tree/main?tab=readme-ov-file#sliceplot). I only can draw a circle but the data points are not chosen as a selection afterwards.. Have you ever encountered that problem?

**Comment by lea-33** [comment]
That's the plan right now. @haesleinhuepf Feel free to say if you would change anything. Otherwise I would work on that! I already have some kind of prototype notebook for this workflow!

- [ ] image-text dict (.json) should not be saved for each pdf , but rather one dict for all pdfs (check if it is already existing when saving the dict and just 'append' data if it does)
- [ ] load dict and create embedding for the texts in it (inspired from [here](https://github.com/haesleinhuepf/stackview/blob/main/docs/sliceplot_datagen.ipynb))

  - [ ] mxbai-embedding
  
  - [ ] UMAP

- [ ] create pd Dataframe for all data

- [ ] interactively plot all images (load them from the dict) and their corresponding umap representation
